sudo: required
services:
  - docker

before_install:
  - docker build -t jithupauljacob/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker ps -a

after_success:
  - docker build -t jithupauljacob/multi-client ./client 
  - docker build -t jithupauljacob/multi-nginx ./nginx
  - docker build -t jithupauljacob/multi-server ./server
  - docker build -t jithupauljacob/multi-worker ./worker   

  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push them to docker hub
  - docker push jithupauljacob/multi-client
  - docker push jithupauljacob/multi-nginx
  - docker push jithupauljacob/multi-server
  - docker push jithupauljacob/multi-worker