sudo: required
services:
  - docker

before_install:
  - echo "Testing Docker Hub credentials"

script:
 - docker ps -a

after_success:
  - docker build -t jithupauljacob/multi-client ./client 
  - docker build -t jithupauljacob/multi-nginx ./nginx
  - docker build -t jithupauljacob/multi-server ./server
  - docker build -t jithupauljacob/multi-worker ./worker   

  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push them to docker hub
  - docker push jithupauljacob/multi-client
  - docker push jithupauljacob/multi-nginx
  - docker push jithupauljacob/multi-server
  - docker push jithupauljacob/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-487596416396
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY   